// <auto-generated />
using LectureEvaluationAPI.Infrastructure.Repositories.MySqlRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LectureEvaluationAPI.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260302155652_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LectureEvaluationAPI.Domain.Entities.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImprovementCritic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.Property<string>("PositiveCritic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LectureId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("LectureEvaluationAPI.Domain.Entities.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("LectureEvaluationAPI.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("LectureEvaluationAPI.Domain.Entities.Lecture", "Lecture")
                        .WithMany("Evaluations")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("LectureEvaluationAPI.Domain.Entities.Lecture", b =>
                {
                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
